// Generated by gencpp from file rosOpenCV/RectMsg.msg
// DO NOT EDIT!


#ifndef ROSOPENCV_MESSAGE_RECTMSG_H
#define ROSOPENCV_MESSAGE_RECTMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rosOpenCV
{
template <class ContainerAllocator>
struct RectMsg_
{
  typedef RectMsg_<ContainerAllocator> Type;

  RectMsg_()
    : header()
    , name()
    , center_x(0)
    , center_y(0)
    , rect_height(0)
    , rect_width(0)  {
    }
  RectMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , center_x(0)
    , center_y(0)
    , rect_height(0)
    , rect_width(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int32_t _center_x_type;
  _center_x_type center_x;

   typedef int32_t _center_y_type;
  _center_y_type center_y;

   typedef int32_t _rect_height_type;
  _rect_height_type rect_height;

   typedef int32_t _rect_width_type;
  _rect_width_type rect_width;





  typedef boost::shared_ptr< ::rosOpenCV::RectMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosOpenCV::RectMsg_<ContainerAllocator> const> ConstPtr;

}; // struct RectMsg_

typedef ::rosOpenCV::RectMsg_<std::allocator<void> > RectMsg;

typedef boost::shared_ptr< ::rosOpenCV::RectMsg > RectMsgPtr;
typedef boost::shared_ptr< ::rosOpenCV::RectMsg const> RectMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosOpenCV::RectMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosOpenCV::RectMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosOpenCV

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rosOpenCV': ['/home/amos/catkin_ws/src/rosOpenCV/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosOpenCV::RectMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosOpenCV::RectMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosOpenCV::RectMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosOpenCV::RectMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosOpenCV::RectMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosOpenCV::RectMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosOpenCV::RectMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "340722c7307f39cbed1c17778a461379";
  }

  static const char* value(const ::rosOpenCV::RectMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x340722c7307f39cbULL;
  static const uint64_t static_value2 = 0xed1c17778a461379ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosOpenCV::RectMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosOpenCV/RectMsg";
  }

  static const char* value(const ::rosOpenCV::RectMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosOpenCV::RectMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
string name\n\
int32 center_x\n\
int32 center_y\n\
int32 rect_height\n\
int32 rect_width\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::rosOpenCV::RectMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosOpenCV::RectMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.center_x);
      stream.next(m.center_y);
      stream.next(m.rect_height);
      stream.next(m.rect_width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RectMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosOpenCV::RectMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosOpenCV::RectMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "center_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_x);
    s << indent << "center_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_y);
    s << indent << "rect_height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rect_height);
    s << indent << "rect_width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rect_width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSOPENCV_MESSAGE_RECTMSG_H
